### ISSUE TITLE
Too many notifications.

### ISSUE THREAD

**Issue by ilyaguy** [wppunk/shipping-nova-poshta-for-woocommerce#95]
![Screenshot from 2020-09-27 22-46-46](https://user-images.githubusercontent.com/6704355/94374226-6971bc80-0113-11eb-92a5-1cc59a64ae9a.png)

Please don't show notification every minute.

**Comment by wppunk** [comment]
@ilyaguy I've fixed this error and pushed it to the WordPress repository. You can update. Thanks for your bug report.

**Comment by ilyaguy** [comment]
Thank you.
